name: Run Sales Portal API tests
permissions:
  contents: write
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.1-noble

    steps:
      - uses: actions/checkout@v4

      - name: Show container OS ID
        run: cat /etc/os-release | grep ^ID

      - name: Install OpenJDK
        run: |
          apt-get update
          apt-get install -y openjdk-17-jre
          echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        id: run-tests
        continue-on-error: true
        env:
          DOTENV_CONFIG_DISABLE: "true"
          SALES_PORTAL_API_URL: ${{ secrets.SALES_PORTAL_API_URL }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: npm run test:api

      - name: Create Allure report
        if: always()
        run: npm run allure-report

      - name: Save Allure report
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: api-regression-report
          path: ./allure-report

      - name: Deploy to GitHub Pages
        id: deploy-report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          destination_dir: allure-report/api

      - name: Notify Telegram with Allure link
        if: ${{ steps.deploy-report.outcome == 'success' }}
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REPORT_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure-report/api/
          TEST_STATUS: ${{ steps.run-tests.outcome }}
        run: |
          TEXT="ðŸ¤– API tests finished with status: ${TEST_STATUS}. Allure report: ${REPORT_URL}"
          curl -s --data-urlencode "chat_id=${TELEGRAM_CHAT_ID}" --data-urlencode "text=${TEXT}" "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage"
